version: '2.2'
services:
  wordpress:
    image: wordpress:fpm
    links:
      - db:mysql
  nginx:
    image: raulr/nginx-wordpress
    links:
      - wordpress
    volumes_from:
      - wordpress
    ports:
      - "8080:80"
    environment:
      POST_MAX_SIZE: 128m
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
  volumes:
    wp:
